### ISSUE TITLE
Project feedback

### ISSUE THREAD

**Issue by adamstep** [juanc27/instawork-challenge-ui#8]
Hi @juanc27 , thanks for the submission, I was able to get it running. I have a couple of suggestions to improve the frontend:
- When deleting a team member, it would be good to ask confirmation to prevent accidental deletions
- When there is only 1 team member, the list says "You Have 1 team members" which is gramatically incorrect (plural)
- It would be nice for validation errors to be rendered next to the related form field, instead of the JSON at the top of the page

Let me know if you are able to make these changes!

Thanks,
Adam

**Comment by juanc27** [comment]
Very good observations/comments. I will make the improvements and let you know. Thanks for the feedback.

**Comment by juanc27** [comment]
Hi @adamstep I made the suggested changes. Let me know if you find anything else. 

Thanks,
Juan

**Comment by adamstep** [comment]
Thanks, all the changes look good!
